// Run with: node tests.cjs. No packages or network required.
const assert=require('node:assert/strict'), fs=require('node:fs'), vm=require('node:vm');
const html=fs.readFileSync(__dirname+'/index.html','utf8');
const json=html.match(/<script type="application\/json" id="edvin-data">([\s\S]*?)<\/script>/)[1];
const src=html.match(/<script id="calculations">([\s\S]*?)<\/script>/)[1];
const box={module:{exports:{}}};vm.runInNewContext(src,box);
const E=box.module.exports,live=JSON.parse(json);
// Frozen regression fixture: new real meals must not invalidate baseline tests.
const fixtures=[['03:30',90],['06:15',60],['08:45',60],['10:00',40],['12:30',80],['14:30',60],['15:30',35],['16:30',60],['18:30',60],['19:00',40],['19:30',50],['21:15',45]];
const D={schemaVersion:2,publishedAt:'2026-09-26T21:52:42+02:00',through:'2026-09-26T21:15:00+02:00',
 days:[{date:'2026-09-24',status:'review',feeds:[],diapers:[]},{date:'2026-09-25',status:'review',feeds:[{at:'2026-09-25T23:00:00+02:00',ml:50,kind:'NAN',verified:true}],diapers:[]},{date:'2026-09-26',status:'partial',feeds:fixtures.map(([t,ml])=>({at:'2026-09-26T'+t+':00+02:00',ml,kind:t==='19:00'?'Morsmelk':'NAN',verified:true,breastfeeding:t==='14:30'})),diapers:['09:30','12:30','14:30','18:30','21:15'].map(t=>({at:'2026-09-26T'+t+':00+02:00',wet:true,stool:null}))}],weights:[{grams:4100},{grams:3900},{grams:3990}]};
const today=D.days[2];
let count=0;function test(name,f){f();console.log('OK',++count,name)}
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-8,`${a} != ${b}`);
const fixture=()=>JSON.parse(JSON.stringify(D));
test('Live data and regression fixture validate',()=>{assert.equal(E.validate(live).length,0);assert.equal(E.validate(D).length,0);});
test('Current day total is 680',()=>assert.equal(E.totals(today).ml,680));
test('12 distinct recorded feed times',()=>assert.equal(E.totals(today).count,12));
test('NAN total 640',()=>assert.equal(E.totals(today).formula,640));
test('Measured breastmilk 40',()=>assert.equal(E.totals(today).breastmilk,40));
test('Unmeasured breastfeeding noted, not added to ml',()=>assert.equal(E.totals(today).nursing,1));
test('Five wet diapers, no duplication',()=>assert.equal(E.totals(today).wet,5));
test('Mean per measured feed',()=>near(E.totals(today).average,680/12));
const day=E.periodStats(D,'2026-09-26',1,false),night=E.periodStats(D,'2026-09-26',1,true);
test('Day total 590',()=>assert.equal(day.ml,590));
test('Day has 11 measured feeds',()=>assert.equal(day.measuredCount,11));
test('Day average is 590/11',()=>near(day.average,590/11));
test('Day interval average 90 minutes',()=>assert.equal(day.gap,90));
test('Day 10 intervals, not 11',()=>assert.equal(day.gapCount,10));
test('Night includes previous 23:00 and 03:30 only',()=>assert.equal(night.count,2));
test('Night average 70 ml',()=>assert.equal(night.average,70));
test('Night interval 270 minutes',()=>assert.equal(night.gap,270));
test('06:15 excluded from night',()=>assert.equal(night.ml,140));
test('Latest day window has only today',()=>assert.equal(E.windowFeeds(D,'2026-09-26',1).length,12));
test('Unreviewed historical days excluded from 7-day histogram',()=>assert.equal(E.windowFeeds(D,'2026-09-26',7).length,12));
test('Older date never includes future records',()=>assert.equal(E.windowFeeds(D,'2026-09-25',1).length,0));
const hist=E.histogram(today.feeds);
test('All eight three-hour bins included',()=>assert.equal(hist.length,8));
test('Histogram count matches feed count',()=>assert.equal(hist.reduce((s,h)=>s+h.count,0),12));
test('Histogram totals sum to daily total',()=>assert.equal(hist.reduce((s,h)=>s+h.total,0),680));
test('Empty bin is null, not zero',()=>assert.equal(hist[0].value,null));
test('12–15 average 70',()=>assert.equal(hist[4].value,70));
test('15–18 average 47.5',()=>assert.equal(hist[5].value,47.5));
test('18–21 average 50',()=>assert.equal(hist[6].value,50));
const points=E.cumulative(today);
test('Cumulative endpoint matches daily total',()=>assert.equal(points.at(-1).total,680));
test('Actual clock location at last feed',()=>assert.equal(points.at(-1).minute,1275));
test('Cumulative is monotonic',()=>assert.ok(points.every((p,i)=>!i||p.total>=points[i-1].total)));
const s=E.scale(680),b={left:56,right:575,top:32,bottom:226};
test('680 chart has 800 upper bound',()=>assert.equal(s.max,800));
test('Axis includes 600 and 800',()=>assert.ok(s.ticks.includes(600)&&s.ticks.includes(800)));
test('680 lies above 600 on shared y scale',()=>assert.ok(E.y(680,s,b.top,b.bottom)<E.y(600,s,b.top,b.bottom)));
test('0 aligns with bottom baseline',()=>assert.equal(E.y(0,s,b.top,b.bottom),b.bottom));
test('680 is exactly 85% of 800 scale',()=>near(b.bottom-E.y(680,s,b.top,b.bottom),.85*(b.bottom-b.top)));
test('Top tick matches top pixel exactly',()=>assert.equal(E.y(s.max,s,b.top,b.bottom),b.top));
test('Proportional heights for every amount',()=>near((b.bottom-E.y(470,s,b.top,b.bottom))/(b.bottom-E.y(680,s,b.top,b.bottom)),470/680));
test('Scale grows above 1200 ml automatically',()=>assert.ok(E.scale(1200).max>1200));
test('Scale grows for unusually large values',()=>assert.ok(E.scale(3500).max>3500));
test('Empty graph gets valid finite scale',()=>assert.ok(E.scale(0).max>0));
test('Cumulative x starts exactly at midnight',()=>assert.equal(E.x(0,b.left,b.right),b.left));
test('Cumulative x ends at next midnight',()=>assert.equal(E.x(1440,b.left,b.right),b.right));
test('Cumulative midday centered',()=>assert.equal(E.x(720,b.left,b.right),(b.left+b.right)/2));
test('Cumulative is step path, not diagonal interpolation',()=>{const p=E.stepPath(points,s,b);assert.equal((p.match(/ H /g)||[]).length,12);assert.equal((p.match(/ V /g)||[]).length,12);assert.ok(!p.includes(' L '));});
test('Weight marks share tick transformation',()=>{let s=E.scale(4.1,3.9,false);near((E.y(3.99,s,32,226)-E.y(4,s,32,226))/(E.y(3.9,s,32,226)-E.y(4,s,32,226)),.1);});
test('Unknown volume not included as zero in average',()=>{const d={feeds:[{ml:null},{ml:60}],diapers:[]};assert.equal(E.totals(d).average,60);assert.equal(E.totals(d).unknown,1);});
test('Unordered input sorted chronologically',()=>assert.equal(E.cumulative({...today,feeds:[...today.feeds].reverse()}).at(-1).total,680));
test('Duplicate feeding fails validation',()=>{let d=fixture();d.days[2].feeds.push(d.days[2].feeds[0]);assert.ok(E.validate(d).length>0);});
test('Negative milk fails validation',()=>{let d=fixture();d.days[2].feeds[0].ml=-1;assert.ok(E.validate(d).length>0);});
test('Duplicate diaper fails validation',()=>{let d=fixture();d.days[2].diapers.push(d.days[2].diapers[0]);assert.ok(E.validate(d).length>0);});
test('New meal updates totals, mean, bins, curve and axis',()=>{let d=fixture();d.through='2026-09-26T21:45:00+02:00';d.days[2].feeds.push({at:d.through,ml:800,kind:'NAN',verified:true});let t=E.totals(d.days[2]);assert.equal(t.ml,1480);assert.equal(t.count,13);assert.equal(E.cumulative(d.days[2]).at(-1).total,1480);assert.ok(E.scale(t.ml).max>1480);assert.equal(E.histogram(d.days[2].feeds)[7].count,2);near(E.periodStats(d,'2026-09-26',1,false).average,1390/12);});
test('00:00 crosses calendar date correctly',()=>assert.equal(E.shift('2026-09-30',1),'2026-10-01'));
test('All live verified days: total equals histogram and curve',()=>{for(const day of live.days.filter(d=>d.status!=='review')){const total=E.totals(day).ml;assert.equal(E.histogram(day.feeds).reduce((s,h)=>s+h.total,0),total);assert.equal(E.cumulative(day).at(-1)?.total||0,total);assert.ok(E.scale(total).max>=total);}});
console.log(`PASS: ${count} checks`);
